import "@/shared/styles/reset.css";
import "@/shared/styles/theme.css";
import type { Metadata } from "next";
import AuthProvider from "./AuthProvider";
import { Providers } from "@/shared/store/providers";
import Modal from "@/shared/components/Modal/Modal";
import Provider from "@/shared/provider/Provider";
import Header from "@/shared/layouts/Header/Header";
import * as styles from "./styles.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Provider>
            <AuthProvider>
              <Modal />
              <Header />
              <main className={styles.main}>{children}</main>
            </AuthProvider>
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
